---
- name: Experiment with set_stats and approvals
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - name: Set a random fact
      ansible.builtin.set_fact:
        my_random_fact: This is a test

    - name: Set stats
      ansible.builtin.set_stats:
        data:
          my_random_stats: Testing stats
