---
#
# Configuration variables for Private Automation Hub
#
ah_remote_registries:
  - "Nexus"
  - "Nexus Proxy"

ah_remotes:
  - name: "rh-validated"
    url: "https://console.redhat.com/api/automation-hub/content/validated/"
    sso_url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
    token: "{{ rh_cloud_ah_token }}"
    requirements: []
    repository: "validated"
  - name: "rh-certified"
    url: "https://console.redhat.com/api/automation-hub/content/published/"
    sso_url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
    token: "{{ rh_cloud_ah_token }}"
    requirements: []
    repository: "rh-certified"
  - name: "community"
    url: "https://galaxy.ansible.com/api/"
    requirements:
      - name: community.general
        version: ">=6.0.0"
      - name: community.crypto
        version: ">=2.0.0"
      - name: community.postgresql
        version: ">=2.0.0"
      - name: community.windows
        version: ">=1.5.0"
      - name: containers.podman
        version: ">=1.8.0"
      - name: community.vmware
        version: ">=2.1.4"
    repository: "community"
...
