---
#
# Playbook to sync remote repositories (Collections) and registries (EE images)
# in Private Automation Hub
#
# This playbook requires the infra.ah_configuration collection version 2.02 or later

- name: Sync remote resources in Private Automation Hub
  hosts: automationhub
  gather_facts: false
  become: false
  tasks:
    - name: "Sync remote registries (EE images)"
      delegate_to: localhost
      infra.ah_configuration.ah_ee_registry_sync:
        ah_host: "{{ inventory_hostname }}"
        ah_username: "{{ ah_admin_user }}"
        ah_password: "{{ ah_admin_password }}"
        interval: 10
        name: "{{ item }}"
        request_timeout: 20
        timeout: 1800
        validate_certs: "{{ validate_certs }}"
        wait: true
      with_items: "{{ ah_remote_registries }}"

    - name: "Sync repositories (Collections)"
      delegate_to: localhost
      infra.ah_configuration.collection_repository_sync:
        ah_host: "{{ inventory_hostname }}"
        ah_username: "{{ ah_admin_user }}"
        ah_password: "{{ ah_admin_password }}"
        interval: 20
        name: "{{ item.repository }}"
        request_timeout: 20
        timeout: 1800
        validate_certs: "{{ validate_certs }}"
        wait: true
      when:
        - ( not item.state is defined ) or ( not item.state == "absent" )
      with_items: "{{ ah_remotes }}"
      async: 7200
      poll: 0
      register: _repo_sync_async
      changed_when: not _repo_sync_async.changed
      no_log: true

    - name: "Sync Repositories | Wait for sync"
      delegate_to: localhost
      ansible.builtin.async_status:
        jid: "{{ _repo_sync_async_results_item.ansible_job_id }}"
      register: _repo_sync_async_result
      until: _repo_sync_async_result.finished
      retries: 120
      delay: 30
      loop: "{{ _repo_sync_async.results }}"
      loop_control:
        loop_var: _repo_sync_async_results_item
      when: _repo_sync_async_results_item.ansible_job_id is defined
      no_log: true
...
